# frozen_string_literal: true

# Shukry CNC Cabinet POC
# Public proof of concept for deterministic SketchUp cabinet generation.
# This file is intentionally small and readable so a client can inspect the approach.

require 'sketchup.rb'

module Shukry
  module CNCCabinetPOC
    extend self

    TAG_PANEL = 'CNC_PANEL'
    TAG_DRILL_5 = 'CNC_DRILL_5MM'
    TAG_DRILL_10 = 'CNC_DRILL_10MM'
    TAG_EDGE = 'CNC_EDGE_BANDING_SCRIBE'
    TAG_GRAIN = 'CNC_GRAIN_DIRECTION'

    def mm(value)
      value.to_f.mm
    end

    def ensure_tag(model, name)
      model.layers[name] || model.layers.add(name)
    end

    def setup_tags(model)
      [TAG_PANEL, TAG_DRILL_5, TAG_DRILL_10, TAG_EDGE, TAG_GRAIN].each do |tag_name|
        ensure_tag(model, tag_name)
      end
    end

    def build_sample_cabinet
      model = Sketchup.active_model
      model.start_operation('Build CNC Cabinet POC', true)
      setup_tags(model)

      root = model.active_entities.add_group
      root.name = 'CAB-001 Sample CNC Cabinet POC'

      add_panel(root.entities, 'P001 left_side', [0, 20, 0], [18, 560, 720], 'vertical')
      add_panel(root.entities, 'P002 right_side', [582, 20, 0], [18, 560, 720], 'vertical')
      add_panel(root.entities, 'P003 bottom', [18, 20, 0], [564, 560, 18], 'horizontal')
      add_panel(root.entities, 'P004 top', [18, 20, 702], [564, 560, 18], 'horizontal')
      add_panel(root.entities, 'P005 back', [0, 560, 0], [600, 9, 720], 'vertical')
      add_panel(root.entities, 'P006 adjustable_shelf', [18, 30, 360], [564, 520, 18], 'horizontal')

      add_drill_circle(root.entities, [0, 30, 96], 5, 10, 'D001 left side hinge')
      add_drill_circle(root.entities, [0, 30, 624], 5, 10, 'D002 left side hinge')
      add_drill_circle(root.entities, [0, 290, 360], 5, 5, 'D003 left side shelf pin')
      add_drill_circle(root.entities, [600, 30, 96], 5, 10, 'D004 right side hinge')
      add_drill_circle(root.entities, [600, 30, 624], 5, 10, 'D005 right side hinge')
      add_drill_circle(root.entities, [600, 290, 360], 5, 5, 'D006 right side shelf pin')

      add_edge_scribe(root.entities, [18, 20, 725], [118, 20, 725], 'front top edge banding sample')
      add_grain_marker(root.entities, [300, 590, 120], [300, 590, 520], 'GRAIN VERTICAL')

      root.set_attribute('cnc_poc', 'source', 'Generated by Shukry CNC Cabinet POC')
      root.set_attribute('cnc_poc', 'intent', 'SketchUp to Aspire CNC vector separation demo')

      model.commit_operation
    rescue StandardError => e
      model.abort_operation
      UI.messagebox("CNC Cabinet POC failed: #{e.message}")
    end

    def add_panel(entities, name, origin_mm, size_mm, grain_direction)
      x, y, z = origin_mm.map { |v| mm(v) }
      sx, sy, sz = size_mm.map { |v| mm(v) }

      group = entities.add_group
      group.name = name
      group.layer = Sketchup.active_model.layers[TAG_PANEL]
      group.set_attribute('cnc_part', 'name', name)
      group.set_attribute('cnc_part', 'grain_direction', grain_direction)
      group.set_attribute('cnc_part', 'size_mm', size_mm.join(' x '))

      pts = [
        Geom::Point3d.new(x, y, z),
        Geom::Point3d.new(x + sx, y, z),
        Geom::Point3d.new(x + sx, y + sy, z),
        Geom::Point3d.new(x, y + sy, z)
      ]
      face = group.entities.add_face(pts)
      face.reverse! if face.normal.z < 0
      face.pushpull(sz)
      group
    end

    def add_drill_circle(entities, center_mm, diameter_mm, depth_mm, label)
      x, y, z = center_mm.map { |v| mm(v) }
      radius = mm(diameter_mm) / 2.0
      tag = depth_mm.to_i == 10 ? TAG_DRILL_10 : TAG_DRILL_5

      group = entities.add_group
      group.name = label
      group.layer = Sketchup.active_model.layers[tag]
      group.set_attribute('cnc_drill', 'diameter_mm', diameter_mm)
      group.set_attribute('cnc_drill', 'depth_mm', depth_mm)
      group.set_attribute('cnc_drill', 'note', 'Flat 2D circle, not a 3D hole')

      # Circle drawn on a vertical XZ plane. This represents a 2D vector on a panel face.
      center = Geom::Point3d.new(x, y, z)
      normal = Geom::Vector3d.new(0, 1, 0)
      group.entities.add_circle(center, normal, radius, 32)
      group
    end

    def add_edge_scribe(entities, start_mm, finish_mm, label)
      group = entities.add_group
      group.name = label
      group.layer = Sketchup.active_model.layers[TAG_EDGE]
      p1 = Geom::Point3d.new(*start_mm.map { |v| mm(v) })
      p2 = Geom::Point3d.new(*finish_mm.map { |v| mm(v) })
      group.entities.add_line(p1, p2)
      group.set_attribute('cnc_edge_banding', 'scribe_length_mm', 100)
      group
    end

    def add_grain_marker(entities, start_mm, finish_mm, text)
      group = entities.add_group
      group.name = text
      group.layer = Sketchup.active_model.layers[TAG_GRAIN]
      p1 = Geom::Point3d.new(*start_mm.map { |v| mm(v) })
      p2 = Geom::Point3d.new(*finish_mm.map { |v| mm(v) })
      group.entities.add_line(p1, p2)
      group.entities.add_text(text, p2)
      group.set_attribute('cnc_grain', 'direction_locked', true)
      group
    end

    unless file_loaded?(__FILE__)
      menu = UI.menu('Extensions').add_submenu('CNC Cabinet POC')
      menu.add_item('Build Sample Cabinet') { build_sample_cabinet }
      file_loaded(__FILE__)
    end
  end
end
